### ISSUE TITLE
Manifest file is broken

### ISSUE THREAD

**Issue by 0xdead8ead** [Juniper/contrail-vnc#8]
Does not work for github. For an "open-source" project, you guys are severely lacking dev onboarding documentation. 

Your instructions located here: http://juniper.github.io/contrail-vnc/README.html

These instructions are incredibly vague, and don't actually provide build instructions. It's laughable that you would call this open source, I'm starting to think this is just another juniper run-around marketing ploy. 

Oh well, more marketing fodder for the RSA booth this year, eh?

**Comment by Groundsea** [comment]
It's unbelivable! almost 4 years passed, I met this issue again! Thank you Chase !
